spring.application.name=backend

spring.datasource.url=${CHATBOT_LLM_DB_URL}
spring.datasource.username=${CHATBOT_LLM_DB_USERNAME}
spring.datasource.password=${CHATBOT_LLM_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

gemini.openai.url=https://generativelanguage.googleapis.com/v1beta/openai/
gemini.api.key=${API_KEY_GEMINI}

jwt.secret=${CHATBOT_LLM_SECRET_KEY}
jwt.expiration=360000000

max.messages.window=20

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB