spring.application.name=backend

spring.datasource.url=${CHATBOT_LLM_DB_URL}
spring.datasource.username=${CHATBOT_LLM_DB_USERNAME}
spring.datasource.password=${CHATBOT_LLM_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
